# Starter pipeline
# https://aka.ms/yaml

trigger:
- master



stages:
- stage: UGHubInstall
  displayName: 'Install via UGhub'
  jobs: 
  - job: UGHubDownload
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
      set MYVAR=foo
      setecho 
  
- stage: CompileTest
  displayName: 'Compile UG4'
  dependsOn: UGHubInstall
  jobs: 
  - job: UGCompile
    steps:
    - bash: echo UGHubDownload
    
 
 
