# Starter pipeline
# https://aka.ms/yaml

trigger:
- master

variables:
  MY_CC: '/usr/bin/clang'
  MY_CXX: '/usr/bin/clang'


stages:
- stage: UGHubInstall
  displayName: 'UG4 via ughub:'
  jobs: 
  - job: UGHubDownload
    displayName: 'build'
    strategy:
      matrix:
        linux-clang:
          imageName: "ubuntu-latest"
          cxxCompiler: '/usr/bin/clang++'
          ccCompiler: '/usr/bin/clang'
          buildName: 'build-linux-clang'
          addString: ''
        linux-gnu:
          imageName: "ubuntu-latest"
          cxxCompiler: '/usr/bin/g++-7'
          ccCompiler: '/usr/bin/gcc-7'
          buildName: 'build-linux-gcc'
          addString: '-DDEBUG'
        mac-clang:
          imageName: "macos-10.13"
          cxxCompiler: '/usr/bin/clang++'
          ccCompiler: '/usr/bin/clang'
          buildName: 'build-mac-clang'
          addString: ''
      maxParallel: 3
    pool:
      vmImage: $(imageName)
      
    steps:
    - script: |
        mkdir "$(System.DefaultWorkingDirectory)/ug4-clone"; 
        cd "$(System.DefaultWorkingDirectory)/ug4-clone";
        git clone https://www.github.com/UG4/ughub
        echo Installed 'ughub'.
        export UG4_FOLDER_SURVIVED_CACHE=false
        if [ -e ug4 ]; then export UG4_FOLDER_SURVIVED_CACHE=true; fi
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then mkdir ug4; fi
        cd ug4
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then ../ughub/ughub init .; fi
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then ../ughub/ughub install ugcore; fi
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then rm -rf ugcore; fi
        ../ughub/ughub install ConvectionDiffusion
        echo "Installed UG4 via ughub"
        
    - script: |
        cd "$(System.DefaultWorkingDirectory)/ug4-clone/ug4";
        mkdir $(buildName); cd $(buildName)
        ls -l ..;
        cmake .. -DCMAKE_CXX_COMPILER"=$(cxxCompiler)" -DCMAKE_C_COMPILER="$(ccCompiler)" -DPARALLEL=OFF -DConvectionDiffusion=ON $(addString)
        
    - script: |
        cd "$(System.DefaultWorkingDirectory)/ug4-clone/ug4";
        ls -l
        cd $(buildName)
        make -j 16;
        
      timeoutInMinutes: 300 
  
  - job: UGCompile
    displayName: 'Compiling'
    dependsOn: UGHubDownload
    pool:
      vmImage: 'ubuntu-latest' 
      strategy:
        matrix:
          Clang-6 Debug:
            CC: 'clang'
            CXX: 'clang++'
            BuildType: Debug
            SelfHost: false
            CMakeArgs: ''

          GCC-7 Debug:
            CC: 'gcc'
            CXX: 'g++'
            BuildType: Debug
            SelfHost: false
            CMakeArgs: ''

    steps:
    - script: ls -l
  
  
  
- stage: SecondStage
  displayName: 'Compile UG4'
  dependsOn: UGHubInstall
  jobs: 
  - job: UGCompile
    steps:
    - script: ls -l
     
    
 
 
