# Starter pipeline
# https://aka.ms/yaml

trigger:
- master



stages:
- stage: UGHubInstall
  displayName: 'Install via UGhub'
  jobs: 
  - job: UGHubDownload
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        mkdir "$(System.DefaultWorkingDirectory)/ug4"; 
        cd "$(System.DefaultWorkingDirectory)/ug4";
        git clone https://www.github.com/UG4/ughub
        echo Installed 'ughub'.
        export UG4_FOLDER_SURVIVED_CACHE=false
        if [ -e ug4 ]; then export UG4_FOLDER_SURVIVED_CACHE=true; fi
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then mkdir ug4; fi
        cd ug4
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then ../ughub/ughub init .; fi
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then ../ughub/ughub install ugcore; fi
        if [[ "$UG4_FOLDER_SURVIVED_CACHE" == "false" ]]; then rm -rf ugcore; fi
        ../ughub/ughub install ConvectionDiffusion
        echo "Installed UG4 via ughub"
        pwd
        cd "$(System.DefaultWorkingDirectory)/ug4";
        mkdir build; cd build
        ls -l ..
        cmake ..
        make -j16echo UGHubDownload
  
- stage: CompileTest
  displayName: 'Compile UG4'
  dependsOn: UGHubInstall
  jobs: 
  - job: UGCompile
    steps:
    - script: |
        cd "$(System.DefaultWorkingDirectory)/ug4";
        mkdir build; cd build
        ls -l ..
        cmake ..
        make -j16echo UGHubDownload
    
 
 
